Add cleanup for existing Docker images
Add cleanup step for existing Docker images before build.

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -34,6 +34,8 @@ jobs:
 
       - name: Build and push Docker image
         run: |
+          docker rmi -f $(docker images | grep 'test-website' | awk '{print $2}') || echo "Not Found"
+          
           TAG=$(date +%Y%m%d%H%M%S)
           echo "Building image with tag: $TAG"
           
